apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: sample-java-app
spec:
  selector:
    matchLabels:
      app: sample-java-app
  template:
    metadata:
      name: demo-pod
      labels:
        app: sample-java-app
    spec:
      containers:
        - name: samplemavenapp
          image: {{.Values.image}}
          ports:
            - containerPort: 8080
  
