apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: NodePort
  selector:
    app: sample-java-app
  ports:
    - port: {{.Values.app.service.port}}
      nodePort: {{.Values.app.service.nodePort}}