pipeline{
    agent any
    environment{
        dockerImage=""
        registryCredentials="dockerhub-creds"
        dockerImageName="vikasharya000/sample-maven-app"
    }
    tools{
        maven("maven-3.9")
    }
    stages{
        stage("Build"){
            steps{
                sh "mvn -B -DskipTests clean package"
            }

        }
        stage("Test"){
            steps{
                sh 'mvn test'
            }
        }
        stage("scan base docker image"){
            steps{
                script {
                    def output = sh(returnStdout: true, script: "grep 'FROM' Dockerfile | awk -F ' ' '{print \$3}'")
                    sh "trivy image ${output} "
                }
            }
        }

        stage("Build docker image"){
            steps{
                script{
                    dockerImage=docker.build dockerImageName + ":${BUILD_NUMBER}"
                }
            }

        }
        stage("Push docker image"){
            steps{
                script{
                    docker.withRegistry('',registryCredentials){
                        dockerImage.push()
                    }
                }
            }

        }
        stage("deploy to kuberneted cluster using helm chart"){
            steps{
                script{
                    kubeconfig(credentialsId: 'kubeconfig') {
                        sh "helm install sample-app ./sample-chart/  --set image=${dockerImage}`"
                    }
                }
            }
        }
        stage('SonarQube analysis') {
            steps {
                withSonarQubeEnv('sonar-server') {
                    sh 'mvn sonar:sonar'
                }
            }
        }
    }

}
