pipeline{
    agent any
    environment{
        dockerImage=""
        registryCredentials="dockerhub-creds"
        dockerImageName="vikasharya000/sample-maven-app"
    }
    tools{
        maven("maven-3.9")
    }
    stages{
        stage("Build"){
            steps{
                sh "mvn -B -DskipTests clean package"
            }

        }
        stage("Test"){
            steps{
                sh 'mvn test'
            }
        }
        stage("Build docker image"){
            steps{
                script{
                    dockerImage=docker.build dockerImageName + ":${BUILD_NUMBER}"
                }
            }

        }
        stage("Push docker image"){
            steps{
                script{
                    docker.withRegistry('',registryCredentials){
                        dockerImage.push()
                    }
                }
            }

        }
        stage("deploy to kuberneted cluster"){
            steps{
                script{
                    kubeconfig(credentialsId: 'kubeconfig') {
                        sh "kubectl apply -f service.yaml -f deployment.yaml"
                    }
                }
            }
        }
        stage("sonarqube analysis"){
            steps{
                echo "yet to complete"
            }
        }
    }

}
